---
- name: Prepara instalacion WL
  hosts: databases
  tasks:

    - name: crea grupo
      group: 
       name: oinstall
       state: present
       gid: 1010

    - name: crea user
      user: 
        name: oracle
        groups: oinstall
        home: /home/oracle
        uid: 1110

    - name: crea rutas
      vars:
        rutas:
          - /u01/software 
          - /u01/app/oracle/middleware
          - /u01/app/oracle/config/domains
          - /u01/app/oracle/config/applications
      file:
        path: "{{ item }}"
        state: directory
      loop: "{{ rutas  }}"      

    - name: Recursively change ownership of a directory
      file:
       path: /u01
       state: directory
       recurse: yes
       owner: oracle
       group: oinstall
       mode: '0775'

    - name: Copia bash_profile
      copy:
        src: /home/tonicom/ansible/pb/wl_install/oracle_bash_profile
        dest: /home/oracle/.bash_profile
        owner: oracle
        group: oracle

    - name: Copia response file
      copy:
        src: /home/tonicom/ansible/pb/wl_install/wls.rsp
        dest: /u01/software/wls.rsp
        owner: oracle
        group: oinstall

    - name: Copia oraInst.loc
      copy:
        src: /home/tonicom/ansible/pb/wl_install/oraInst.loc
        dest: /u01/software/oraInst.loc
        owner: oracle
        group: oinstall

    - name: copia java
      unarchive:
        remote_src: no
        src: /home/tonicom/jdk-8u201-linux-x64.tar.gz
        dest: /u01/software
        owner: oracle
        group: oinstall

    - name: Ejecuta instalacion
      become: yes
      become_user: oracle
      shell:  
#       "source /home/oracle/.bash_profile &&  /u01/software/jdk1.8.0_201/bin/java -Xmx1024m -jar fmw_12.2.1.3.0_wls.jar -silent -responseFile /u01/software/wls.rsp -invPtrLoc /u01/software/oraInst.loc"
        "/u01/software/jdk1.8.0_201/bin/java -Xmx1024m -jar fmw_12.2.1.3.0_wls.jar -silent -responseFile /u01/software/wls.rsp -invPtrLoc /u01/software/oraInst.loc"

      args:
        chdir: /home/oracle
      register: wlout

    - debug: msg="{{wlout.stdout}}" 

       
